name: Run Tests

# Execute this workflow only for PRs/Pushes to your develop branch
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      
# Execute a job called "Tests" once for each combination of defined nim-versions and os's.
# It will execute only on ubuntu-latest (but you can expand as displayed).
# For execution it will install the package according to the nimble file
# and then run the nimble command that executes the tests 
jobs:
  Tests:
    strategy:
      matrix:
        nim-version: ['1.6.2', '2.0.0'] # All nim versions you may want to test for
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    timeout-minutes: 30

    runs-on: ${{ matrix.os }}
    name: Nim ${{ matrix.nim-version }}

    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - run: nimble install -Y

      - name: Run your tests
        run: nimble test
