name: Run Tests

# Execute this workflow only for PRs/Pushes to your develop branch
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
      
permissions:
  contents: write
  id-token: write
  
# Execute a job called "Tests" once for each combination of defined nim-versions and os's.
# It will execute only on ubuntu-latest (but you can expand as displayed).
# For execution it will install the package according to the nimble file
# and then run the nimble command that executes the tests 
jobs:
  Tests:
    strategy:
      matrix:
        nimversion: 
          - binary:2.0.0
          - binary:1.6.10
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    name: Nim ${{ matrix.nimversion }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: iffy/install-nim@v4
        with:
          version: ${{ matrix.nimversion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: |
          nimble install -y
          nimble test